### ISSUE TITLE
Some suggestions/questions

### ISSUE THREAD

**Issue by grantmcdermott** [cran-task-views/Econometrics#16]
Marking down quickly, as I have to switch to another project and don't want to forget:

- Should **modelsummary** be bumped to `priority="core"`? I know this is covered by the ReproducibleResearch TV, but I can't help but feel that the Econometrics TV should include at lease one dedicated table-exporting package among the core group.
- Packages to add: [**penppml**](https://cran.r-project.org/web/packages/penppml/index.html) and a couple from the [easystats](https://easystats.github.io/easystats/) suite (or, maybe just highlight [**performance**](https://cran.r-project.org/web/packages/performance/) as an example).

**Comment by zeileis** [comment]
* If you feel strongly about `modelsummary`, feel free to bump it to core. In my opinion it is not specific enough for econometrics for that. But clearly many applied econometricians will find the package useful so I'm not strongly opposed either.
* `penpml` seems to fit well. `performance` is a bit generic (and not so specific to econometrics) but might help some users, I guess.

**Comment by zeileis** [comment]
Grant @grantmcdermott, do you still want to add any of the changes above? If so, it would be great! Otherwise it might be time to close the issue?

**Comment by grantmcdermott** [comment]
Upon reflection, I agree with you about `modelsummary`. Will try to add `penppml` soon and give a bit more thought to `performance`...
