### ISSUE TITLE
fwildclusterboot has been removed from CRAN since November

### ISSUE THREAD

**Issue by s3alfisc** [cran-task-views/Econometrics#17]
Hi all,

I just wanted to let you know that `fwildclusterboot` has been [removed from CRAN ](https://cran.r-project.org/web/packages/fwildclusterboot/index.html) since early November. I have swiftly resubmitted a fixed version, and for more than two months now, the package has been pending a manual inspection from a CRAN team member. As no one is replying to my emails, I am unfortunately not sure what is going on and how things will proceed. 

Best, Alex

**Comment by zeileis** [comment]
Thanks for letting us know. I've sent an e-mail to the CRAN team to see whether I can help. Will report here if I hear anything back.

**Comment by s3alfisc** [comment]
Thanks, Achim, that is very much appreciated!

**Comment by zeileis** [comment]
I've had some quick feedback from a CRAN team member and he promised he would look into it in the next days.

**Comment by s3alfisc** [comment]
That is great news! Once again, thanks for helping with this! =)

**Comment by s3alfisc** [comment]
And the package is back on [CRAN](https://cran.r-project.org/web/packages/fwildclusterboot/index.html)! 🥳

**Comment by zeileis** [comment]
Apologies for the long delay! I'm happy we could finally close this issue.

Thank you for your work on the package!

**Comment by grantmcdermott** [comment]
Good news!
