### ISSUE TITLE
Package 'fwildclusterboot' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/Econometrics#18]
Package [fwildclusterboot](https://CRAN.R-project.org/package=fwildclusterboot) is currently listed in CRAN Task View [Econometrics](https://CRAN.R-project.org/view=Econometrics) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by zeileis** [comment]
The author has tried to resurrect the package in November but is waiting for a follow-up from the CRAN team, see:
https://github.com/cran-task-views/Econometrics/issues/17

**Comment by s3alfisc** [comment]
The package is back on CRAN, see #17 🎈.
