### ISSUE TITLE
Additional maintainers

### ISSUE THREAD

**Issue by zeileis** [cran-task-views/Econometrics#2]
To get more input and distribute the workload a bit more, it might be a good idea to add one or two further co-maintainers for the task view. @grantmcdermott do you have any suggestions for this?

Ideally we would have enthusiastic econometricians using R that have a good overview of the package ecosystem and are willing to volunteer for a project like this. Maybe we should ask Andrew Heiss? A female contributor would also be great. Any thoughts?

**Comment by grantmcdermott** [comment]
Definitely have a few names in mind. I think it would be good to get people adjacent to econ (e.g. poli sci) too. Should I reach out to some folks to gauge up-front interest/availability and we can take it from there?

**Comment by zeileis** [comment]
With political science I'm not sure whether we should have a joint task view or maybe encourage the creation of a separate _PoliticalScience_ view. Do you have any thoughts on this?

My feeling is that political science uses a lot from econometrics, from psychometrics but then also brings dedicated special methods on analyzing voting behavior, roll calls, elections, etc. But maybe a dedicated specific _Psephology_ task view (or something along those lines) would be better than a general _PoliticalScience_ task view which is likely too broad.

Another separate task view that would be useful could be _CausalInference_.

**Comment by zeileis** [comment]
Just for the record:

* [Kevin Tappe](https://github.com/tappek), who has been the most active contributor to the task view over the last years, has now officially joined as a co-maintainer.
* A _CausalInference_ task view has now been officially proposed and already received positive feedback from some of the CRAN Task View Editors: <https://github.com/cran-task-views/ctv/issues/15>.

**Comment by zeileis** [comment]
Given that we are a team of three now, I'm closing this issue for now. Of course, if anyone of you @grantmcdermott or @tappek has good ideas in the future - especially regarding a female co-maintainer - please bring it up.
