### ISSUE TITLE
Package 'ivprobit' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by kurthornik** [cran-task-views/Econometrics#24]
Package [ivprobit](https://CRAN.R-project.org/package=ivprobit) is currently listed in CRAN Task View [Econometrics](https://CRAN.R-project.org/view=Econometrics) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.  See the section on _CRAN package archivals_ in the [maintenance guidelines](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md) for more details.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by zeileis** [comment]
I've contacted the author (https://github.com/zedtaha/ivprobit-1.0/issues/6) and the issues would be relatively straightforward to fix. But given the lack of activity in the repository since 2018 I'm not too optimistic, unfortunately.

**Comment by zeileis** [comment]
Now removed in https://github.com/cran-task-views/Econometrics/commit/f9198d1b7bc15c76fb67454199ef81317b00d498
