### ISSUE TITLE
Minor suggestion

### ISSUE THREAD

**Issue by grantmcdermott** [cran-task-views/Econometrics#4]
Erring on the side of parsimony, I advocate we avoid putting in parentheses (1) references to "base" libraries and  (2) previous packages that have been subsumed. 

Example of (1):  _Ordinary least squares (OLS) estimation for linear models is provided by lm() **(from stats)** and..._

Example of (2): _Two-stage least squares (2SLS) is provided by r pkg("ivreg") **(previously in r pkg("AER"))**..._

It's good to pay homage, but I don't think we gain anything from the reader's perspective.

**Comment by zeileis** [comment]
The base package names are there for completeness (and general education). If you feel that they are distracting for many users, feel free to drop them.

In case of (2) my intention was not to pay homage to myself. I rather thought that there are many books/papers/blogs/tutorials out there that say `ivreg()` is from `AER`. So it was mainly to let readers know that they should use the `ivreg` package where they were might have been instructed to use `AER`. If you have a good idea for a better concise formulation, feel free to use it.

**Comment by grantmcdermott** [comment]
Perfect. I'll take a look through later.

PS. Sorry, my phrasing with "homage" wasn't quite right (and certainly not suggesting that you were patting yourself on the back... though you quite deserve to!) I meant it in the sense you described: does tracing the lineage help or distract the reader? I'll think on your request RE another way to phrase it.

**Comment by zeileis** [comment]
Great, thanks. No worries re phrasing!

**Comment by zeileis** [comment]
Did you have the chance to have another look at this @grantmcdermott ? Can we close the issue?
