### ISSUE TITLE
candidate `fwildclusterboot`

### ISSUE THREAD

**Issue by tappek** [cran-task-views/Econometrics#6]
We might consider to include pkg `fwildcusterboot`.
https://cran.r-project.org/web/packages/fwildclusterboot/

I did not try it but it looks well from the "outside". Currently, its maintainer declares it as lifecycle = experimental (see badge here: https://s3alfisc.github.io/fwildclusterboot/).

**Comment by zeileis** [comment]
Sure, go ahead. I think the natural place is to include it in the Miscellaneous/Bootstrap section.

**Comment by grantmcdermott** [comment]
I know the package. Can confirm it's cool. The same author has also put together an alternative with bindings to the [Julia implementation](https://github.com/s3alfisc/wildboottestjlr), which gives a major speed boost. But I don't think it's on CRAN yet.

**Comment by tappek** [comment]
closed via d15b536255ea5422a2f880809d816daa5228cc99

**Comment by zeileis** [comment]
Gee, @tappek, you are quick! Thanks for closing the issue.

(I received an e-mail from the `fwildclusterboot` author on another matter and hence was looking a bit at his blog and results discussed there. Hence I thought I would do the task view addition now but did not get round yet to close the issue, yet.)

**Comment by tappek** [comment]
Thanks for adding the text for `fwildclusterboot`, @zeileis!
I happend I saw the package was added but the issue was still open... I did not realize the commit was perfomed just a few minutes before - so I closed the issue ;)
