### ISSUE TITLE
When to update version

### ISSUE THREAD

**Issue by tappek** [cran-task-views/Econometrics#9]
Is there any guidance when we would update the version of this task view (or in general for the task views)? 

All I found is "`version` is specified by a date in ISO 8601 format (yyyy-mm-dd)" (in https://github.com/cran-task-views/ctv/blob/main/Documentation.md).

Is adding (or removing) a package on a day-wise resolution the trigger?
Minor text refinements do not warrant a new version?
Will it be you @zeileis to change the version?

**Comment by grantmcdermott** [comment]
Was also wondering about this...

**Comment by zeileis** [comment]
The idea is that whenever you change something, you should update the `version`.

**Comment by tappek** [comment]
Thanks, I did a version bump to a more recent date in 7a507908b9661f6353beecca114568bc70236c2d

**Comment by zeileis** [comment]
Great, thanks! Updated on CRAN as well.
